site_name: E2Q Docs
nav:
  - Home: index.md
  - 安装: Installation.md
  - 快速开始: Quickstart.md
  - 代码讲解: BaseCode.md 
  - E2L 语言: e2l.md
  - E2L 语言 API: e2l_api.md
  - E2Q Protocol: e2q_protocol.md
  - 关于: about.md
theme: readthedocs
